export class Share {
    static customers = [
    {
      id: 1000,
      name: 'James Smith',
      country: { name: 'USA', code: 'us' },
      representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
      date: '2020-05-01',
      status: 'qualified',
      verified: true,
      activity: 80,
      balance: 120500
    },
    {
      id: 1001,
      name: 'Maria Rodriguez',
      country: { name: 'Mexico', code: 'mx' },
      representative: { name: 'Anna Fali', image: 'annafali.png' },
      date: '2020-06-15',
      status: 'new',
      verified: false,
      activity: 45,
      balance: 85000
    },
    {
      id: 1002,
      name: 'David Wilson',
      country: { name: 'Canada', code: 'ca' },
      representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
      date: '2020-07-20',
      status: 'negotiation',
      verified: true,
      activity: 95,
      balance: 220500
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1003,
      name: 'Sophie Turner',
      country: { name: 'UK', code: 'gb' },
      representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      date: '2020-08-10',
      status: 'renewal',
      verified: true,
      activity: 75,
      balance: 165000
    },
    {
      id: 1004,
      name: 'Hans Weber',
      country: { name: 'Germany', code: 'de' },
      representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
      date: '2020-09-25',
      status: 'proposal',
      verified: false,
      activity: 60,
      balance: 95400
    }
  ];
}